services:
  postgres-test:
    image: postgres:16-alpine
    container_name: fichas_gem_test_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: fichas_gem_test
    ports:
      - "5434:5432"
    tmpfs:
      - /var/lib/postgresql/data
